const MINUTE_IN_MS = 60_000;
const REFERENCE_DATA_STALE_TIME_MINUTES = 5;
const USER_DATA_STALE_TIME_MINUTES = 5;

export const REFERENCE_DATA_STALE_TIME_MS =
  REFERENCE_DATA_STALE_TIME_MINUTES * MINUTE_IN_MS;
export const USER_DATA_STALE_TIME_MS =
  USER_DATA_STALE_TIME_MINUTES * MINUTE_IN_MS;
