/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedSettingsRouteRouteImport } from './routes/_protected/settings/route'
import { Route as ApiWebhooksResendRouteImport } from './routes/api/webhooks/resend'
import { Route as ApiSubscriptionsExportRouteImport } from './routes/api/subscriptions/export'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedSettingsNotificationsRouteImport } from './routes/_protected/settings/notifications'
import { Route as ProtectedCCollectionIdRouteRouteImport } from './routes/_protected/c.$collectionId/route'
import { Route as ProtectedCCollectionIdSubscriptionsRouteImport } from './routes/_protected/c.$collectionId/subscriptions'
import { Route as ProtectedCCollectionIdSettingsRouteImport } from './routes/_protected/c.$collectionId/settings'
import { Route as ProtectedCCollectionIdInvoicesRouteImport } from './routes/_protected/c.$collectionId/invoices'
import { Route as ProtectedCCollectionIdDashboardRouteImport } from './routes/_protected/c.$collectionId/dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSettingsRouteRoute = ProtectedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ApiWebhooksResendRoute = ApiWebhooksResendRouteImport.update({
  id: '/api/webhooks/resend',
  path: '/api/webhooks/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionsExportRoute = ApiSubscriptionsExportRouteImport.update({
  id: '/api/subscriptions/export',
  path: '/api/subscriptions/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsNotificationsRoute =
  ProtectedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedCCollectionIdRouteRoute =
  ProtectedCCollectionIdRouteRouteImport.update({
    id: '/c/$collectionId',
    path: '/c/$collectionId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedCCollectionIdSubscriptionsRoute =
  ProtectedCCollectionIdSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => ProtectedCCollectionIdRouteRoute,
  } as any)
const ProtectedCCollectionIdSettingsRoute =
  ProtectedCCollectionIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedCCollectionIdRouteRoute,
  } as any)
const ProtectedCCollectionIdInvoicesRoute =
  ProtectedCCollectionIdInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => ProtectedCCollectionIdRouteRoute,
  } as any)
const ProtectedCCollectionIdDashboardRoute =
  ProtectedCCollectionIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProtectedCCollectionIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof ProtectedSettingsRouteRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/c/$collectionId': typeof ProtectedCCollectionIdRouteRouteWithChildren
  '/settings/notifications': typeof ProtectedSettingsNotificationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/subscriptions/export': typeof ApiSubscriptionsExportRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/c/$collectionId/dashboard': typeof ProtectedCCollectionIdDashboardRoute
  '/c/$collectionId/invoices': typeof ProtectedCCollectionIdInvoicesRoute
  '/c/$collectionId/settings': typeof ProtectedCCollectionIdSettingsRoute
  '/c/$collectionId/subscriptions': typeof ProtectedCCollectionIdSubscriptionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof ProtectedSettingsRouteRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/c/$collectionId': typeof ProtectedCCollectionIdRouteRouteWithChildren
  '/settings/notifications': typeof ProtectedSettingsNotificationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/subscriptions/export': typeof ApiSubscriptionsExportRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/c/$collectionId/dashboard': typeof ProtectedCCollectionIdDashboardRoute
  '/c/$collectionId/invoices': typeof ProtectedCCollectionIdInvoicesRoute
  '/c/$collectionId/settings': typeof ProtectedCCollectionIdSettingsRoute
  '/c/$collectionId/subscriptions': typeof ProtectedCCollectionIdSubscriptionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/settings': typeof ProtectedSettingsRouteRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/_protected/c/$collectionId': typeof ProtectedCCollectionIdRouteRouteWithChildren
  '/_protected/settings/notifications': typeof ProtectedSettingsNotificationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/subscriptions/export': typeof ApiSubscriptionsExportRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/_protected/c/$collectionId/dashboard': typeof ProtectedCCollectionIdDashboardRoute
  '/_protected/c/$collectionId/invoices': typeof ProtectedCCollectionIdInvoicesRoute
  '/_protected/c/$collectionId/settings': typeof ProtectedCCollectionIdSettingsRoute
  '/_protected/c/$collectionId/subscriptions': typeof ProtectedCCollectionIdSubscriptionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/dashboard'
    | '/api/health'
    | '/c/$collectionId'
    | '/settings/notifications'
    | '/api/auth/$'
    | '/api/subscriptions/export'
    | '/api/webhooks/resend'
    | '/c/$collectionId/dashboard'
    | '/c/$collectionId/invoices'
    | '/c/$collectionId/settings'
    | '/c/$collectionId/subscriptions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/dashboard'
    | '/api/health'
    | '/c/$collectionId'
    | '/settings/notifications'
    | '/api/auth/$'
    | '/api/subscriptions/export'
    | '/api/webhooks/resend'
    | '/c/$collectionId/dashboard'
    | '/c/$collectionId/invoices'
    | '/c/$collectionId/settings'
    | '/c/$collectionId/subscriptions'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/settings'
    | '/_protected/dashboard'
    | '/api/health'
    | '/_protected/c/$collectionId'
    | '/_protected/settings/notifications'
    | '/api/auth/$'
    | '/api/subscriptions/export'
    | '/api/webhooks/resend'
    | '/_protected/c/$collectionId/dashboard'
    | '/_protected/c/$collectionId/invoices'
    | '/_protected/c/$collectionId/settings'
    | '/_protected/c/$collectionId/subscriptions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSubscriptionsExportRoute: typeof ApiSubscriptionsExportRoute
  ApiWebhooksResendRoute: typeof ApiWebhooksResendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/api/webhooks/resend': {
      id: '/api/webhooks/resend'
      path: '/api/webhooks/resend'
      fullPath: '/api/webhooks/resend'
      preLoaderRoute: typeof ApiWebhooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscriptions/export': {
      id: '/api/subscriptions/export'
      path: '/api/subscriptions/export'
      fullPath: '/api/subscriptions/export'
      preLoaderRoute: typeof ApiSubscriptionsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings/notifications': {
      id: '/_protected/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof ProtectedSettingsNotificationsRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/c/$collectionId': {
      id: '/_protected/c/$collectionId'
      path: '/c/$collectionId'
      fullPath: '/c/$collectionId'
      preLoaderRoute: typeof ProtectedCCollectionIdRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/c/$collectionId/subscriptions': {
      id: '/_protected/c/$collectionId/subscriptions'
      path: '/subscriptions'
      fullPath: '/c/$collectionId/subscriptions'
      preLoaderRoute: typeof ProtectedCCollectionIdSubscriptionsRouteImport
      parentRoute: typeof ProtectedCCollectionIdRouteRoute
    }
    '/_protected/c/$collectionId/settings': {
      id: '/_protected/c/$collectionId/settings'
      path: '/settings'
      fullPath: '/c/$collectionId/settings'
      preLoaderRoute: typeof ProtectedCCollectionIdSettingsRouteImport
      parentRoute: typeof ProtectedCCollectionIdRouteRoute
    }
    '/_protected/c/$collectionId/invoices': {
      id: '/_protected/c/$collectionId/invoices'
      path: '/invoices'
      fullPath: '/c/$collectionId/invoices'
      preLoaderRoute: typeof ProtectedCCollectionIdInvoicesRouteImport
      parentRoute: typeof ProtectedCCollectionIdRouteRoute
    }
    '/_protected/c/$collectionId/dashboard': {
      id: '/_protected/c/$collectionId/dashboard'
      path: '/dashboard'
      fullPath: '/c/$collectionId/dashboard'
      preLoaderRoute: typeof ProtectedCCollectionIdDashboardRouteImport
      parentRoute: typeof ProtectedCCollectionIdRouteRoute
    }
  }
}

interface ProtectedSettingsRouteRouteChildren {
  ProtectedSettingsNotificationsRoute: typeof ProtectedSettingsNotificationsRoute
}

const ProtectedSettingsRouteRouteChildren: ProtectedSettingsRouteRouteChildren =
  {
    ProtectedSettingsNotificationsRoute: ProtectedSettingsNotificationsRoute,
  }

const ProtectedSettingsRouteRouteWithChildren =
  ProtectedSettingsRouteRoute._addFileChildren(
    ProtectedSettingsRouteRouteChildren,
  )

interface ProtectedCCollectionIdRouteRouteChildren {
  ProtectedCCollectionIdDashboardRoute: typeof ProtectedCCollectionIdDashboardRoute
  ProtectedCCollectionIdInvoicesRoute: typeof ProtectedCCollectionIdInvoicesRoute
  ProtectedCCollectionIdSettingsRoute: typeof ProtectedCCollectionIdSettingsRoute
  ProtectedCCollectionIdSubscriptionsRoute: typeof ProtectedCCollectionIdSubscriptionsRoute
}

const ProtectedCCollectionIdRouteRouteChildren: ProtectedCCollectionIdRouteRouteChildren =
  {
    ProtectedCCollectionIdDashboardRoute: ProtectedCCollectionIdDashboardRoute,
    ProtectedCCollectionIdInvoicesRoute: ProtectedCCollectionIdInvoicesRoute,
    ProtectedCCollectionIdSettingsRoute: ProtectedCCollectionIdSettingsRoute,
    ProtectedCCollectionIdSubscriptionsRoute:
      ProtectedCCollectionIdSubscriptionsRoute,
  }

const ProtectedCCollectionIdRouteRouteWithChildren =
  ProtectedCCollectionIdRouteRoute._addFileChildren(
    ProtectedCCollectionIdRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedSettingsRouteRoute: typeof ProtectedSettingsRouteRouteWithChildren
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedCCollectionIdRouteRoute: typeof ProtectedCCollectionIdRouteRouteWithChildren
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedSettingsRouteRoute: ProtectedSettingsRouteRouteWithChildren,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedCCollectionIdRouteRoute:
    ProtectedCCollectionIdRouteRouteWithChildren,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSubscriptionsExportRoute: ApiSubscriptionsExportRoute,
  ApiWebhooksResendRoute: ApiWebhooksResendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
