/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ApiSubscriptionsExportRouteImport } from './routes/api/subscriptions/export'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedCCollectionIdSubscriptionsRouteImport } from './routes/_protected/c.$collectionId/subscriptions'
import { Route as ProtectedCCollectionIdSettingsRouteImport } from './routes/_protected/c.$collectionId/settings'
import { Route as ProtectedCCollectionIdInvoicesRouteImport } from './routes/_protected/c.$collectionId/invoices'
import { Route as ProtectedCCollectionIdDashboardRouteImport } from './routes/_protected/c.$collectionId/dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ApiSubscriptionsExportRoute = ApiSubscriptionsExportRouteImport.update({
  id: '/api/subscriptions/export',
  path: '/api/subscriptions/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedCCollectionIdSubscriptionsRoute =
  ProtectedCCollectionIdSubscriptionsRouteImport.update({
    id: '/c/$collectionId/subscriptions',
    path: '/c/$collectionId/subscriptions',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedCCollectionIdSettingsRoute =
  ProtectedCCollectionIdSettingsRouteImport.update({
    id: '/c/$collectionId/settings',
    path: '/c/$collectionId/settings',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedCCollectionIdInvoicesRoute =
  ProtectedCCollectionIdInvoicesRouteImport.update({
    id: '/c/$collectionId/invoices',
    path: '/c/$collectionId/invoices',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedCCollectionIdDashboardRoute =
  ProtectedCCollectionIdDashboardRouteImport.update({
    id: '/c/$collectionId/dashboard',
    path: '/c/$collectionId/dashboard',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/subscriptions/export': typeof ApiSubscriptionsExportRoute
  '/c/$collectionId/dashboard': typeof ProtectedCCollectionIdDashboardRoute
  '/c/$collectionId/invoices': typeof ProtectedCCollectionIdInvoicesRoute
  '/c/$collectionId/settings': typeof ProtectedCCollectionIdSettingsRoute
  '/c/$collectionId/subscriptions': typeof ProtectedCCollectionIdSubscriptionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/subscriptions/export': typeof ApiSubscriptionsExportRoute
  '/c/$collectionId/dashboard': typeof ProtectedCCollectionIdDashboardRoute
  '/c/$collectionId/invoices': typeof ProtectedCCollectionIdInvoicesRoute
  '/c/$collectionId/settings': typeof ProtectedCCollectionIdSettingsRoute
  '/c/$collectionId/subscriptions': typeof ProtectedCCollectionIdSubscriptionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/subscriptions/export': typeof ApiSubscriptionsExportRoute
  '/_protected/c/$collectionId/dashboard': typeof ProtectedCCollectionIdDashboardRoute
  '/_protected/c/$collectionId/invoices': typeof ProtectedCCollectionIdInvoicesRoute
  '/_protected/c/$collectionId/settings': typeof ProtectedCCollectionIdSettingsRoute
  '/_protected/c/$collectionId/subscriptions': typeof ProtectedCCollectionIdSubscriptionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/subscriptions/export'
    | '/c/$collectionId/dashboard'
    | '/c/$collectionId/invoices'
    | '/c/$collectionId/settings'
    | '/c/$collectionId/subscriptions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/subscriptions/export'
    | '/c/$collectionId/dashboard'
    | '/c/$collectionId/invoices'
    | '/c/$collectionId/settings'
    | '/c/$collectionId/subscriptions'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/about'
    | '/login'
    | '/_protected/dashboard'
    | '/api/auth/$'
    | '/api/subscriptions/export'
    | '/_protected/c/$collectionId/dashboard'
    | '/_protected/c/$collectionId/invoices'
    | '/_protected/c/$collectionId/settings'
    | '/_protected/c/$collectionId/subscriptions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSubscriptionsExportRoute: typeof ApiSubscriptionsExportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/api/subscriptions/export': {
      id: '/api/subscriptions/export'
      path: '/api/subscriptions/export'
      fullPath: '/api/subscriptions/export'
      preLoaderRoute: typeof ApiSubscriptionsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/c/$collectionId/subscriptions': {
      id: '/_protected/c/$collectionId/subscriptions'
      path: '/c/$collectionId/subscriptions'
      fullPath: '/c/$collectionId/subscriptions'
      preLoaderRoute: typeof ProtectedCCollectionIdSubscriptionsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/c/$collectionId/settings': {
      id: '/_protected/c/$collectionId/settings'
      path: '/c/$collectionId/settings'
      fullPath: '/c/$collectionId/settings'
      preLoaderRoute: typeof ProtectedCCollectionIdSettingsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/c/$collectionId/invoices': {
      id: '/_protected/c/$collectionId/invoices'
      path: '/c/$collectionId/invoices'
      fullPath: '/c/$collectionId/invoices'
      preLoaderRoute: typeof ProtectedCCollectionIdInvoicesRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/c/$collectionId/dashboard': {
      id: '/_protected/c/$collectionId/dashboard'
      path: '/c/$collectionId/dashboard'
      fullPath: '/c/$collectionId/dashboard'
      preLoaderRoute: typeof ProtectedCCollectionIdDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedCCollectionIdDashboardRoute: typeof ProtectedCCollectionIdDashboardRoute
  ProtectedCCollectionIdInvoicesRoute: typeof ProtectedCCollectionIdInvoicesRoute
  ProtectedCCollectionIdSettingsRoute: typeof ProtectedCCollectionIdSettingsRoute
  ProtectedCCollectionIdSubscriptionsRoute: typeof ProtectedCCollectionIdSubscriptionsRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedCCollectionIdDashboardRoute: ProtectedCCollectionIdDashboardRoute,
  ProtectedCCollectionIdInvoicesRoute: ProtectedCCollectionIdInvoicesRoute,
  ProtectedCCollectionIdSettingsRoute: ProtectedCCollectionIdSettingsRoute,
  ProtectedCCollectionIdSubscriptionsRoute:
    ProtectedCCollectionIdSubscriptionsRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSubscriptionsExportRoute: ApiSubscriptionsExportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
